use std::fs;
use std::io::Result;
use std::path::Path;

use audit_agent_core::finding::Finding;

pub fn generate_regression_tests(findings: &[Finding]) -> RegressionTestSuite {
    if findings.is_empty() {
        return RegressionTestSuite {
            crypto_tests: None,
            kani_harnesses: vec![],
            madsim_scenarios: vec![],
        };
    }

    let mut tests = String::new();
    tests.push_str("#[cfg(test)]\n");
    tests.push_str("mod generated_crypto_regressions {\n");
    tests.push_str("    #[test]\n");
    tests.push_str("    fn generated_regression_placeholders() {\n");
    tests.push_str("        let findings = [\n");
    for finding in findings {
        tests.push_str(&format!("            \"{}\",\n", finding.id));
    }
    tests.push_str("        ];\n");
    tests.push_str("        assert!(!findings.is_empty());\n");
    tests.push_str("    }\n");
    tests.push_str("}\n");

    RegressionTestSuite {
        crypto_tests: Some(tests),
        kani_harnesses: vec![],
        madsim_scenarios: vec![],
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RegressionTestSuite {
    pub crypto_tests: Option<String>,
    pub kani_harnesses: Vec<KaniHarness>,
    pub madsim_scenarios: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KaniHarness {
    pub finding_id: String,
    pub source: String,
}

pub fn write_phase1_output_layout(
    output_dir: &Path,
    report_technical_markdown: &str,
    findings_json: &str,
    findings_sarif: &str,
    evidence_pack_zip: &Path,
    audit_manifest_json: &str,
    regression: &RegressionTestSuite,
) -> Result<()> {
    fs::create_dir_all(output_dir)?;
    fs::create_dir_all(output_dir.join("regression-tests"))?;
    fs::create_dir_all(output_dir.join("regression-tests/kani_harnesses"))?;
    fs::create_dir_all(output_dir.join("regression-tests/madsim_scenarios"))?;

    fs::write(
        output_dir.join("report-executive.md"),
        "# Executive Summary\n\nGenerated by audit-agent.\n",
    )?;
    fs::write(
        output_dir.join("report-technical.md"),
        report_technical_markdown,
    )?;
    fs::write(output_dir.join("findings.json"), findings_json)?;
    fs::write(output_dir.join("findings.sarif"), findings_sarif)?;
    fs::copy(evidence_pack_zip, output_dir.join("evidence-pack.zip"))?;
    fs::write(output_dir.join("audit-manifest.json"), audit_manifest_json)?;

    let crypto_tests = regression.crypto_tests.as_deref().unwrap_or(
        "#[cfg(test)]\nmod generated_crypto_regressions {\n    #[test]\n    fn placeholder() { assert!(true); }\n}\n",
    );
    fs::write(
        output_dir.join("regression-tests/crypto_misuse_tests.rs"),
        crypto_tests,
    )?;

    Ok(())
}
